### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by notariuss** [LuckPerms/LuckPermsWeb#408]
When building code to static, i'm getting next error:
```
-  Building for production...
Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:67:19)
    at Object.createHash (node:crypto:135:10)
    at module.exports (/tmp/build/node_modules/webpack/lib/util/createHash.js:135:53)
    at NormalModule._initBuildHash (/tmp/build/node_modules/webpack/lib/NormalModule.js:417:16)
    at handleParseError (/tmp/build/node_modules/webpack/lib/NormalModule.js:471:10)
    at /tmp/build/node_modules/webpack/lib/NormalModule.js:503:5
    at /tmp/build/node_modules/webpack/lib/NormalModule.js:358:12
    at /tmp/build/node_modules/loader-runner/lib/LoaderRunner.js:373:3
    at iterateNormalLoaders (/tmp/build/node_modules/loader-runner/lib/LoaderRunner.js:214:10)
    at iterateNormalLoaders (/tmp/build/node_modules/loader-runner/lib/LoaderRunner.js:221:10)
    at /tmp/build/node_modules/loader-runner/lib/LoaderRunner.js:236:3
    at runSyncOrAsync (/tmp/build/node_modules/loader-runner/lib/LoaderRunner.js:130:11)
    at iterateNormalLoaders (/tmp/build/node_modules/loader-runner/lib/LoaderRunner.js:232:2)
    at Array.<anonymous> (/tmp/build/node_modules/loader-runner/lib/LoaderRunner.js:205:4)
    at Storage.finished (/tmp/build/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:55:16)
    at /tmp/build/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:91:9
Browserslist: caniuse-lite is outdated. Please run the following command: `npm update`
/tmp/build/node_modules/loader-runner/lib/LoaderRunner.js:114
                        throw e;
                        ^

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:67:19)
    at Object.createHash (node:crypto:135:10)
    at module.exports (/tmp/build/node_modules/webpack/lib/util/createHash.js:135:53)
    at NormalModule._initBuildHash (/tmp/build/node_modules/webpack/lib/NormalModule.js:417:16)
    at handleParseError (/tmp/build/node_modules/webpack/lib/NormalModule.js:471:10)
    at /tmp/build/node_modules/webpack/lib/NormalModule.js:503:5
    at /tmp/build/node_modules/webpack/lib/NormalModule.js:358:12
    at /tmp/build/node_modules/loader-runner/lib/LoaderRunner.js:373:3
    at iterateNormalLoaders (/tmp/build/node_modules/loader-runner/lib/LoaderRunner.js:214:10)
    at iterateNormalLoaders (/tmp/build/node_modules/loader-runner/lib/LoaderRunner.js:221:10)
    at /tmp/build/node_modules/loader-runner/lib/LoaderRunner.js:236:3
    at context.callback (/tmp/build/node_modules/loader-runner/lib/LoaderRunner.js:111:13)
    at /tmp/build/node_modules/cache-loader/dist/index.js:118:7
    at /tmp/build/node_modules/graceful-fs/graceful-fs.js:45:10
    at FSReqCallback.oncomplete (node:fs:188:23) {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}

Node.js v17.8.0
```

**Comment by Turbotailz** [comment]
Sorry for the late reply (you probably fixed this already) but this is an issue with your version of node (v17).

Note that odd-numbered versions of Node are usually experimental and you should avoid using these versions. Even-numbered releases of Node are more stable and get LTS making them more reliable.

Either downgrade to Node v16 or upgrade to v18.
